#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-
# 代码有问题别找我！虽然是我写的，并且我觉得它是没问题的，如果不是你的操作原因，或许是它自己长歪了！
# Licensed under the GNU LGPL v2.1 - http://www.gnu.org/licenses/lgpl.html

"""
Run with:
python ./setup.py install
"""
__title__ = 'setup.py'
__version__ = '0.1.2'
__author__ = 'Joey Hwong <joeyhwong@hotmail.com>'
__mtime__ = '20:32 01/15 2016'

from setuptools import setup, find_packages
from os.path import join, dirname
import sys

if sys.version_info[:2] < (2, 6):
	raise Exception('This version of gensim needs Python 2.6 or later.')

setup(name='Rhea_Chip',
      version=__version__,
      description='A Simple pipeline for the analysis of human data generated by NGS approaches.',
      packages=find_packages(),
      author=__author__,
      author_email='joeyhwong@hotmail.com',
      install_requires=['pysam', 'numpy', 'matplotlib', 'smart_open', 'toolz', 'xlsxwriter', 'statsmodels'],
      include_package_data=True,
      long_description=open(join(dirname(__file__), 'README')).read(),
      scripts=['Rhea_Chip/Rhea_Chip_pipeline.py'],
      )
