#! /usr/bin/env python2.7
# -*- coding: utf-8 -*-
# 代码有问题别找我！虽然是我写的，并且我觉得它是没问题的，如果不是你的操作原因，或许是它自己长歪了！

__author__ = 'Joey Hwong <joeyhwong@hotmail.com>'
__url__ = 'https://github.com/ZhiweiHwang/Rhea_Chip'
__mtime__ = '20:53 01/15 2016'
__description__ = 'A Simple pipeline for the analysis of human data generated by NGS approaches.'
__version__ = '0.1.2'
__note__ = "Please specify environment variable Rhea_Chip_Home as the home of Rhea_Chip pipeline."

